; Auto-generated. Do not edit!


(cl:in-package multi_robot-msg)


;//! \htmlinclude gotoGoal.msg.html

(cl:defclass <gotoGoal> (roslisp-msg-protocol:ros-message)
  ((order
    :reader order
    :initarg :order
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0)))
)

(cl:defclass gotoGoal (<gotoGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <gotoGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'gotoGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name multi_robot-msg:<gotoGoal> is deprecated: use multi_robot-msg:gotoGoal instead.")))

(cl:ensure-generic-function 'order-val :lambda-list '(m))
(cl:defmethod order-val ((m <gotoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader multi_robot-msg:order-val is deprecated.  Use multi_robot-msg:order instead.")
  (order m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <gotoGoal>) ostream)
  "Serializes a message object of type '<gotoGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'order))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'order))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <gotoGoal>) istream)
  "Deserializes a message object of type '<gotoGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'order) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'order)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<gotoGoal>)))
  "Returns string type for a message object of type '<gotoGoal>"
  "multi_robot/gotoGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'gotoGoal)))
  "Returns string type for a message object of type 'gotoGoal"
  "multi_robot/gotoGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<gotoGoal>)))
  "Returns md5sum for a message object of type '<gotoGoal>"
  "b5edba87f02b289938819f83435372db")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'gotoGoal)))
  "Returns md5sum for a message object of type 'gotoGoal"
  "b5edba87f02b289938819f83435372db")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<gotoGoal>)))
  "Returns full string definition for message of type '<gotoGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32[] order~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'gotoGoal)))
  "Returns full string definition for message of type 'gotoGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32[] order~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <gotoGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'order) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <gotoGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'gotoGoal
    (cl:cons ':order (order msg))
))
